### ISSUE TITLE
Python 2 EOL

### ISSUE THREAD

**Issue by jazzace** [univ-of-utah-marriott-library-apple/display_manager#19]
While Python 2.7 is still available in macOS, it is no longer being updated as of April 2020. For continued use, this tool will need to be rewritten for Python 3. (The use of Greg Neagle's [Relocatable Python](https://github.com/gregneagle/relocatable-python) may be useful for final deployment.) I do not have the coding skills to write it, but would be willing to help test.

**Comment by uurazzle** [comment]
Hi @jazzace, I discussed this with our team and we will work on this as a low priority project. We will let you know when we are to the point to start testing, etc.

**Comment by jazzace** [comment]
Looks like you have updated the code to Python3. ReadMe needs fixing, but this issue appears to be addressed.

**Comment by uurazzle** [comment]
Hi @jazzace:

Thanks, for the note. Due to a lack the bandwidth & other higher priorities, we will probably not be able to get to this for a little while. If there is interest in updating the "Readme" and submitting a pull request it would be much appreciated.

Any interest, in contributing to this project?

**Comment by jazzace** [comment]
I will definitely see if I can make a documentation PR.
