### ISSUE TITLE
Is this compatible with macOS Sequoia?

### ISSUE THREAD

**Issue by ZaLiTHkA** [univ-of-utah-marriott-library-apple/display_manager#34]
I have a 2020 MacBook Pro M1, updated to the latest macOS release (`15.1`, as of writing this).

unfortunately, I ended up persisting some funky external display configuration that severely limits the use of my one and only external display... I've got a thread open on the Apple Support Forums (going on 2 weeks now, 50+ views, zero replies).

then I found a Stack Overflow post from a few years back that mentioned this package, and now here I am...

---

when I download the latest release `dmg` file and try launch `DisplayManager-1.0.2.pkg`, macOS refuses to run it, telling me "Apple could not verify it is free of malware".

I see the project itself has had some updates since `1.0.2`, with the latest commit from August 2023, but still the latest release is from back in 2019.

I've tried everything short of a full factory reset, which I'm leaving as an absolute last resort (especially since I've seen some users report that even *that* did not resolve their issues).

is anybody able to help with getting this up and running now in 2024?

**Comment by uurazzle** [comment]
Hi:

Thanks for your feedback.

Unfortunately, due to other priorities and limited time and resources.

We haven't updated this project in a very long time.

I would suggest investigating other alternatives to meet your needs like...

##### BetterDisplay

BetterDisplay is a macOS application developed by @waydabber (Kodeon Software) that enhances display management with advanced features for Apple Silicon and Intel Macs. Key capabilities include custom resolutions, flexible HiDPI scaling, XDR/HDR brightness upscaling, virtual screens, picture-in-picture (PIP) mode, display configuration overrides, DDC (Display Data Channel) control, and EDID manipulation. The app supports creating adaptive display layouts, syncing display settings, and advanced color and brightness controls. It also features command-line integration and macOS Shortcuts support. The latest v3.x version is compatible with macOS Sequoia, Sonoma, and Ventura.

Pro Features (requires a $19 license) include extended brightness control, full DDC support, layout protection, and customizable keyboard shortcuts. A 14-day trial is available, with many features accessible for free for non-commercial use.

[https://github.com/waydabber/BetterDisplay](https://github.com/waydabber/BetterDisplay)

##### MonitorControl

MonitorControl is an open-source macOS app that allows users to control external display brightness, volume, and contrast, integrating seamlessly with macOS for a native-like experience. Users can use keyboard shortcuts, including standard Apple keys, or a menubar slider for adjustments. It supports multiple protocols such as DDC for external displays and software-based dimming for virtual or unsupported screens. The app is highly customizable and compatible with macOS versions from Catalina 10.15 onward, with specific requirements for newer macOS versions.

The project is maintained by @waydabber and has contributions from numerous developers. It is built using Swift, with dependencies like MediaKeyTap and Sparkle. The source code is accessible on GitHub, and users can contribute by making donations or submitting pull requests. The app is licensed under MIT, boasts over 28,000 stars, and is recognized for its robust feature set.

[https://github.com/MonitorControl/MonitorControl](https://github.com/MonitorControl/MonitorControl)

Good luck...

**Comment by ZaLiTHkA** [comment]
hi @uurazzle, thanks for the links, I'll definitely check them out. I'm rather new to the Apple world (new work PC), so I'll gladly take all the advice I can get.

**Comment by ZaLiTHkA** [comment]
quick follow up, in case anybody else has the same issue... BetterDisplay Pro did indeed help me solve this one, [more details here](https://github.com/waydabber/BetterDisplay/discussions/3656).
