### ISSUE TITLE
What happened to `set` and `show exact`?

### ISSUE THREAD

**Issue by tjluoma** [univ-of-utah-marriott-library-apple/display_manager#6]
I had some scripts that were using `display_manager.py show exact` and ` display_manager.py set closest` and they no longer seem to work. In fact, they no longer seem to exist at all.

**Comment by ahdavies6** [comment]
@tjluoma:

Regarding `show exact`: please see the relevant section of our documentation [here](https://github.com/univ-of-utah-marriott-library-apple/display_manager#show). The `exact` subcommand was present in the pre-release version of Display Manager a few years ago, but has since been deprecated. All future versions of Display Manager should include backwards-compatible syntax. To achieve the same result, make sure you format calls to `display_manager.py` as specified [here](https://github.com/univ-of-utah-marriott-library-apple/display_manager#show).

Regarding `set closest`: there is no `set` command in Display Manager -- this is another feature that has been deprecated since v0.9.3. [Res](https://github.com/univ-of-utah-marriott-library-apple/display_manager#res) should suit your needs -- specifically, if you're using the old `set closest` syntax, you'll achieve the same result via `$ display_manager.py res <width> <height>` (e.g. `$ display_manager.py res 1920 1080` for a 1920x1080 resolution), with parameters `refresh`, `options`, and `scope` now optional, and `color depth` deprecated (as all modern monitors now use consistent color depth values across all Display Modes, which is almost always `32` (for 32-bit depth)).
